//****************************************************************************
// @Module        Capture / Compare Unit 6 (CCU6)
// @Filename      CC6.H
// @Project       Boost1.dav
//----------------------------------------------------------------------------
// @Controller    Infineon XC822M-1F
//
// @Compiler      Keil
//
// @Codegenerator 0.08
//
// @Description   This file contains all function prototypes and macros for 
//                the CCU6 module.
//
//----------------------------------------------------------------------------
// @Date          08.01.2010 22:23:03
//
//****************************************************************************

// USER CODE BEGIN (CCU6_Header,1)

// USER CODE END



#ifndef _CC6_H_
#define _CC6_H_

//****************************************************************************
// @Project Includes
//****************************************************************************

// USER CODE BEGIN (CCU6_Header,2)

// USER CODE END


//****************************************************************************
// @Macros
//****************************************************************************

// USER CODE BEGIN (CCU6_Header,3)

// USER CODE END


//****************************************************************************
// @Defines
//****************************************************************************

//   This parameter identifies CC6 timer 12
#define CC6_TIMER_12 12

//   This parameter identifies CC6 timer 13
#define CC6_TIMER_13 13

//   This parameter identifies CC6 channel 0
#define CC6_CHANNEL_0 0

//   This parameter identifies CC6 channel 1
#define CC6_CHANNEL_1 1

//   This parameter identifies CC6 channel 2
#define CC6_CHANNEL_2 2

//   This parameter identifies CC6 channel 3
#define CC6_CHANNEL_3 3


// USER CODE BEGIN (CCU6_Header,4)

// USER CODE END


//****************************************************************************
// @Typedefs
//****************************************************************************

// USER CODE BEGIN (CCU6_Header,5)

// USER CODE END


//****************************************************************************
// @Imported Global Variables
//****************************************************************************

// USER CODE BEGIN (CCU6_Header,6)

// USER CODE END


//****************************************************************************
// @Global Variables
//****************************************************************************

// USER CODE BEGIN (CCU6_Header,7)

// USER CODE END


//****************************************************************************
// @Prototypes Of Global Functions
//****************************************************************************

void CC6_vInit(void);


// USER CODE BEGIN (CCU6_Header,8)

// USER CODE END


//****************************************************************************
// @Interrupt Vectors
//****************************************************************************



// USER CODE BEGIN (CCU6_Header,10)

// USER CODE END


#endif  // ifndef _CC6_H_
